# Travis Lint : https://lint.travis-ci.org
# Config secure
language: java
jdk:
  - oraclejdk8
notifications:
  slack: 
    secure: "ExpIuHBgYpH/pg1AbhWUpwFQAVrR8PkboA6i2N1L7UjLO50VgLa/ObSohIMjk3X7KDJdk4GE6CccpKm5P9hb99K6Nih8Inowg5aPKIZYAu8KQ41v7pPv2GHSsKNXv+RvVo7vYgEdrEPsab17Ok8dQei0bkV7/wuNYxA2JE94xEH9I3nWXaOT4A2sPhX+rlOQApToMUYJ4YOPU9drtrENwscjlAXMPoKG6nVHNo7+Ho6YNUhjifWiRUMBfDyIZihPwjEAXqAOdm7PzJAS0EkrcSONurNX4Qv9QwVie04w3IbQd2BXJiBJGuNU38owjbbc0epQOJA96UKcbI2ms1tdqAYSa/Mjl47Mg6DmKX37lZs3qOeaAeoVD4yN/83AeGoAck9UMY96riDN/YXbcPL30Ga0wDNEVe84udjLtBUk9Cciy4FsRCuo6WAfAgvEV+Vp+2CFxq4P32CO3wRA2ki8ooByv2f8hioU564dOkd6Sc0Hud5ZPHxbB5/b1aUfgcmN/kIeBjRioAxdTeNFhisb8OpjRboxHFuJMdEvxu1y6e05WLyOuvhpjrNZ0YIoTldr86Emm9K3eIf2n4gxJ8mS0eqlkwJO7qO4p5x+zioMbeo7s6UCqi8uVkDMYO04IdngVqSNg1zISY1HZjK85ufySo+aIgx7iFcoH3hgrJyMaRU="
install: 
  - gradle fatJar
before_deploy:
  - cd build/libs
deploy:
  provider: releases
  api_key:
    secure: AnE5pum8lCyymw8F+S64vTOBk/238dZk503YwO0ecTPzhnscqnYfm/eqdF0wGiReptSFVLJ3FBeCpzWWmV5+yPo9D3ZO/8nFOyxmrvwwm+tb8AcjFFf1oMdmZ5IqFDifHiR2X27raDmNmlSqSBsI7E53FoQRVVseshOzP8NjJGqq1fvNJ4OKZ28YlTg8jMtFQSfBnVi0uhvK7nw1VjOaG9tMCUvGNodCiTaWuw5LP2noaV26Ewwbn3FastEUMUHij5p8gXkTDjk+xq/LSZA3+IqZe19Sxy4hWyUyO3hmPPsy4YSaxuuX2x+8Fa1+wi6YOWQklLCtFTLXeWQnwhqz2ZwanRE6e6nguqd16jd2el3TH4N/ND+C3sYqIzX1kt3VZL/17oCnvRL3j7ToJrb2unBeCM2E1j/BlpR/X5KhX9+jZV4LAj2ZF0w4KrcC0K4ds0hPWaV9YGAVWT9u5TaDcwNHXdehQ8M0uTMb/gMHogLx/UNNbd80ShhFTqbhRBd6eFWgxSmq6YiDUeRg/U2N9ooVLsmPE/EkPzr+13d03hXMlHxOku+dQy9cqtAj+7ziwYnUWL0C2TFJP/CWB5KSk/tSBfQR+w3/IQu5Do21VQOerzRX2BkhBHUwHV+wvp2B5bqnuqAJ5JIyaE4+NESrFvVe+TlGoo5qF3SHGkDENIc=
  file: BoxCryptorInventoryViewer.jar
  skip_cleanup: true  
  on:
    repo: vzwingma/BoxCryptorInventoryViewer
    tags: true